<?php
/**
 */

namespace execut\files\bootstrap;


use execut\files\Attacher;
use execut\files\Module;
use execut\yii\Bootstrap;

class Common extends Bootstrap
{
    public $_defaultDepends = [
        'modules' => [
            'files' => [
                'class' => Module::class
            ],
        ],
    ];

    public function bootstrap($app)
    {
        parent::bootstrap($app); // TODO: Change the autogenerated stub

        $this->attachToModules();
    }

    protected function attachToModules() {
        $models = \yii::$app->getModule('files')->getAttachedModels();
        $tables = [];
        foreach ($models as $model) {
            $tables[] = $model::tableName();
        }

        $attacher = new Attacher([
            'tables' => $tables,
        ]);

        $attacher->safeUp();
    }
}