<?php
/**
 */

namespace execut\files\models;


class FileBackend extends File
{
    public static function find()
    {
        return parent::find()->withoutData(); // TODO: Change the autogenerated stub
    }
}